kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
  namespace: poly-airflow
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-083248a4759bf99ca
  directoryPerms: "755"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional

---
{{/*aws efs create-access-point --file-system-id fs-059c26ae2d8c90a76*/}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-efs-pv
  namespace: poly-airflow
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-083248a4759bf99ca::fsap-0e5f23d6a8d3f0113
---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-logs
  namespace: poly-airflow
  labels:
    app: airflow
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
