apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cluster-access
  namespace: poly-airflow
  labels:
    app: airflow
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
