version: '2.4'

services:
  db:
    container_name: db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    restart: always

  airflow:
    container_name: build
    build:
      context: ../
      args:
        SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db/airflow

  webserver:
    container_name: web
    extends:
      service: airflow
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      - db
    env_file: "./dev.env"
    volumes:
      - "../src/dags:/usr/local/airflow/dags"
      - "../src/jobs:/usr/local/airflow/jobs"
      - "../src/tools:/usr/local/airflow/tools"
      - "../src/sqls:/usr/local/airflow/sqls"
      - "../src/jobs:/usr/local/airflow/bash"
      - "./airflow.cfg:/usr/local/airflow/airflow.cfg"
      - "./entrypoint.sh:/usr/local/airflow/entrypoint.sh"
    entrypoint: "/usr/local/airflow/entrypoint.sh"