version: '2.1'

services:

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  base:
    build:
      context: ../
      args:
        - PIP_EXTRA_INDEX_URL=$PIP_EXTRA_INDEX_URL
        - NEXUS_HOST=$NEXUS_HOST

  webserver:
    extends:
      service: base
    ports:
      - "8083:8080"
    depends_on:
      - postgres
    env_file: ../.devcontainer/dev.env
    environment:
      - AIRFLOW_ENV=dev
    volumes:
      - "./entrypoint.sh:/usr/local/airflow/entrypoint.sh"
      - "./airflow.cfg:/usr/local/airflow/airflow.cfg"
      - "../src/dags:/usr/local/airflow/dags"
      - "../src/jobs:/usr/local/airflow/jobs"
      - "../src/tools:/usr/local/airflow/tools"
      - "../src/sqls:/usr/local/airflow/sqls"
      - "../src/jobs:/usr/local/airflow/bash"
      - "../dbt:/usr/local/dbt"
    entrypoint: "./entrypoint.sh"

  dev:
    extends:
      service: base
    command: "bash"
    depends_on:
      - postgres
    volumes:
      - "../src/dags:/usr/local/airflow/dags"
      - "../src/jobs:/usr/local/airflow/jobs"
      - "../src/tools:/usr/local/airflow/tools"
      - "../src/sqls:/usr/local/airflow/sqls"
      - "../src/jobs:/usr/local/airflow/bash"
      - "../tests:/usr/local/airflow/tests"
      - "../dbt:/usr/local/dbt"
    env_file: ../.devcontainer/dev.env

  vs-dev:
    extends:
      service: base
    command: "sleep infinity"
    depends_on:
      - postgres
    volumes:
      - "../src/dags:/usr/local/airflow/dags"
      - "../src/jobs:/usr/local/airflow/jobs"
      - "../src/tools:/usr/local/airflow/tools"
      - "../src/sqls:/usr/local/airflow/sqls"
      - "../src/jobs:/usr/local/airflow/bash"
      - "../tests:/usr/local/airflow/tests"
      - "../dbt:/usr/local/dbt"
    env_file: ../.devcontainer/dev.env


  test:
    extends:
      service: base
    command: "py.test"

