version: '2.4'

services:
  db:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    restart: always
    networks:
      local:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  af:
    container_name: build
    build:
      context: ../
      dockerfile: DockerfileLocal
      args:
        - SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
        - CORE__FERNET_KEY=bgcmnw69Rw6qqP42imvHumCa_FxizhErQr5Gf6HPErQ=
        - CORE__DAGS_FOLDER=/usr/local/airflow/dags
        - API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
    restart: always
    networks:
      local:

  webs:
    container_name: web
    extends:
      service: af
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 60s
      retries: 5
    restart: always
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - "../src/dags:/usr/local/airflow/dags"
      - "../src/jobs:/usr/local/airflow/jobs"
      - "../src/tools:/usr/local/airflow/tools"
      - "../src/sqls:/usr/local/airflow/sqls"
      - "../src/jobs:/usr/local/airflow/bash"
      - "./entrypoint.sh:/usr/local/airflow/entrypoint.sh"
    entrypoint: "/usr/local/airflow/entrypoint.sh"
    networks:
      local:

networks:
  local:

volumes:
  postgres-db-volume: