version: '2.1'

services:

  postgres:
    image: postgres:13
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  base:
    build:
      context: ../
      args:
        SQL_ALCHEMY_CONN: postgresql://airflow:airflow@postgres/airflow

  webserver:
    extends:
      service: base
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file: ./dev.env
    #    environment:
    #      AIRFLOW_ENV: dev
    #      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    #      # For backward compatibility, with Airflow <2.3
    #      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - "./airflow.cfg:/usr/local/airflow/airflow.cfg"
      - "../src/dags:/usr/local/airflow/dags"
      - "../src/jobs:/usr/local/airflow/jobs"
      - "../src/tools:/usr/local/airflow/tools"
      - "../src/sqls:/usr/local/airflow/sqls"
      - "../src/jobs:/usr/local/airflow/bash"
#    entrypoint: "./entrypoint.sh"



#networks:
#  postgres:
#
#volumes:
#  postgres:
#    driver: local